sudo: required

language: php
php:
#- '7.1'
- '7.2'
#- '7.3'
#- '7.4'
#- nightly
before_install:
- composer config --global github-oauth.github.com $GITHUB_TOKEN
before_script:
- composer install
notifications:
  email:
    recipients:
    - alabard@gmail.com
    on_success: change
    on_failure: change
env:
  global:
    secure: qcEMYIWFZgWGxYtO1m5rLJVHMlkLf1+b2NfONITFhysqZD/y1hfRmIrIB16xUhgUJn41a4uacQ0eIwQB03kArLAn15X7VYvp0uMnyICrTjyv9v5eK1112ueVd/NI4TLEfhJOmWatqhGJl3wo4TdOFCVstuZiiOaH6hh7vGrq2SThfnNZfn6tmYc10SpMJnACURJEAZoHTHJaEY39KwYL/y0zaOI/H5Kp1akXInM9CpQc/lW0B5GGFo9Fupkwu3ILYeddce0ZzYKirMbZai7k1xW0XZ5JA/5R33OOtloXdLlKA+01mXjy1BKHuZ2TzPA+8Bh9kH8izeAyTiRIDhf+YVy9gmUZ71yOfRYYu/3rNUnrBruJeDoFVWLrFqDut8+Qe8teh0PELGq1EK82poMSQYd5UapJl/cJL8dm692nuZ24kMcT4XJIu47qhLH1D5ywzykjzhgnwPRmiiRNU5lUIe6WP5Dkr+AhYBXeEqkXO5nFvQa+w5cua1hCcmKNyMXkiRFf3eKTZhV9cNJ4v6H3yeOQ6RSn3NlygUcU+03rAHeBSdOlRJWPbu6itcD1y+INngLh1akkwXf6J/ZUWDf5KWOcPwJsQ9QHe6ycZ4WhCcIsYDsGINwAzM5qKbouSKeiGmI3tyh5ZgpXlqfOX3xrS/X5CLZbvT+LuuYB7+PZoB4=
