# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
    schedule:
        - cron: '0 0 1 * *'
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ['lts/*']
                php-versions: ['7.3', '7.4', '8.0', '8.1']
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm i -g grunt-cli
            - run: npm install
            - run: grunt

            - uses: shivammathur/setup-php@v2
              with:
                  php-version:  ${{ matrix.php-versions }}
                  coverage: xdebug

            - name: tests
              run: |
                  composer install --no-progress --ignore-platform-reqs
                  XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text
